export interface CountryItem {
  code: string;
  name: string;
}

export const COUNTRIES_LIST: CountryItem[] = [
  { code: "All", name: "All Countries 🌐" },
  
  // High-Priority Trade & Maritime Hubs
  { code: "Singapore", name: "Singapore 🇸🇬" },
  { code: "India", name: "India 🇮🇳" },
  { code: "Germany", name: "Germany 🇩🇪" },
  { code: "Japan", name: "Japan 🇯🇵" },
  { code: "USA", name: "United States 🇺🇸" },
  { code: "Netherlands", name: "Netherlands 🇳🇱" },
  { code: "Sweden", name: "Sweden 🇸🇪" },
  { code: "China", name: "China 🇨🇳" },
  { code: "UAE", name: "United Arab Emirates 🇦🇪" },
  { code: "Norway", name: "Norway 🇳🇴" },
  { code: "United Kingdom", name: "United Kingdom 🇬🇧" },
  { code: "South Korea", name: "South Korea 🇰🇷" },
  { code: "Australia", name: "Australia 🇦🇺" },
  
  // Alphabetical listing of all countries
  { code: "Afghanistan", name: "Afghanistan 🇦_f" },
  { code: "Albania", name: "Albania 🇦🇱" },
  { code: "Algeria", name: "Algeria 🇩🇿" },
  { code: "Andorra", name: "Andorra 🇦🇩" },
  { code: "Angola", name: "Angola 🇦🇴" },
  { code: "Antigua and Barbuda", name: "Antigua and Barbuda 🇦🇬" },
  { code: "Argentina", name: "Argentina 🇦🇷" },
  { code: "Armenia", name: "Armenia 🇦🇲" },
  { code: "Austria", name: "Austria 🇦🇹" },
  { code: "Azerbaijan", name: "Azerbaijan 🇦🇿" },
  { code: "Bahamas", name: "Bahamas 🇧🇸" },
  { code: "Bahrain", name: "Bahrain 🇧🇭" },
  { code: "Bangladesh", name: "Bangladesh 🇧🇩" },
  { code: "Barbados", name: "Barbados 🇧🇧" },
  { code: "Belarus", name: "Belarus 🇧🇾" },
  { code: "Belgium", name: "Belgium 🇧🇪" },
  { code: "Belize", name: "Belize 🇧🇿" },
  { code: "Benin", name: "Benin 🇧_j" },
  { code: "Bhutan", name: "Bhutan 🇧_t" },
  { code: "Bolivia", name: "Bolivia 🇧🇴" },
  { code: "Bosnia and Herzegovina", name: "Bosnia & Herzegovina 🇧🇦" },
  { code: "Botswana", name: "Botswana 🇧🇼" },
  { code: "Brazil", name: "Brazil 🇧🇷" },
  { code: "Brunei", name: "Brunei 🇧_n" },
  { code: "Bulgaria", name: "Bulgaria 🇧🇬" },
  { code: "Burkina Faso", name: "Burkina Faso 🇧_f" },
  { code: "Burundi", name: "Burundi 🇧_i" },
  { code: "Cabo Verde", name: "Cabo Verde 🇨_v" },
  { code: "Cambodia", name: "Cambodia 🇰_h" },
  { code: "Cameroon", name: "Cameroon 🇨_m" },
  { code: "Canada", name: "Canada 🇨🇦" },
  { code: "Central African Republic", name: "Central African Republic 🇨_f" },
  { code: "Chad", name: "Chad 🇹_d" },
  { code: "Chile", name: "Chile 🇨🇱" },
  { code: "Colombia", name: "Colombia 🇨🇴" },
  { code: "Comoros", name: "Comoros 🇰_m" },
  { code: "Congo", name: "Congo 🇨_g" },
  { code: "Costa Rica", name: "Costa Rica 🇨_r" },
  { code: "Croatia", name: "Croatia 🇭_r" },
  { code: "Cuba", name: "Cuba 🇨_u" },
  { code: "Cyprus", name: "Cyprus 🇨_y" },
  { code: "Czechia", name: "Czechia 🇨_z" },
  { code: "Denmark", name: "Denmark 🇩🇰" },
  { code: "Djibouti", name: "Djibouti 🇩_j" },
  { code: "Dominica", name: "Dominica 🇩_m" },
  { code: "Dominican Republic", name: "Dominican Republic 🇩_o" },
  { code: "Ecuador", name: "Ecuador 🇪_c" },
  { code: "Egypt", name: "Egypt 🇪🇬" },
  { code: "El Salvador", name: "El Salvador 🇸_v" },
  { code: "Equatorial Guinea", name: "Equatorial Guinea 🇬_q" },
  { code: "Eritrea", name: "Eritrea 🇪_r" },
  { code: "Estonia", name: "Estonia 🇪🇪" },
  { code: "Eswatini", name: "Eswatini 🇸_z" },
  { code: "Ethiopia", name: "Ethiopia 🇪_t" },
  { code: "Fiji", name: "Fiji 🇫_j" },
  { code: "Finland", name: "Finland 🇫_i" },
  { code: "France", name: "France 🇫🇷" },
  { code: "Gabon", name: "Gabon 🇬_a" },
  { code: "Gambia", name: "Gambia 🇬_m" },
  { code: "Georgia", name: "Georgia 🇬_e" },
  { code: "Ghana", name: "Ghana 🇬_h" },
  { code: "Greece", name: "Greece 🇬🇷" },
  { code: "Grenada", name: "Grenada 🇬_d" },
  { code: "Guatemala", name: "Guatemala 🇬_t" },
  { code: "Guinea", name: "Guinea 🇬_n" },
  { code: "Guinea-Bissau", name: "Guinea-Bissau 🇬_w" },
  { code: "Guyana", name: "Guyana 🇬_y" },
  { code: "Haiti", name: "Haiti 🇭_t" },
  { code: "Honduras", name: "Honduras 🇭_n" },
  { code: "Hungary", name: "Hungary 🇭🇺" },
  { code: "Iceland", name: "Iceland 🇮🇸" },
  { code: "Indonesia", name: "Indonesia 🇮🇩" },
  { code: "Iran", name: "Iran 🇮🇷" },
  { code: "Iraq", name: "Iraq 🇮🇶" },
  { code: "Ireland", name: "Ireland 🇮🇪" },
  { code: "Israel", name: "Israel 🇮🇱" },
  { code: "Italy", name: "Italy 🇮🇹" },
  { code: "Jamaica", name: "Jamaica 🇯_m" },
  { code: "Jordan", name: "Jordan 🇯🇴" },
  { code: "Kazakhstan", name: "Kazakhstan 🇰🇿" },
  { code: "Kenya", name: "Kenya 🇰🇪" },
  { code: "Kiribati", name: "Kiribati 🇰_i" },
  { code: "Kuwait", name: "Kuwait 🇰🇼" },
  { code: "Kyrgyzstan", name: "Kyrgyzstan 🇰🇬" },
  { code: "Laos", name: "Laos 🇱_a" },
  { code: "Latvia", name: "Latvia 🇱🇻" },
  { code: "Lebanon", name: "Lebanon 🇱🇧" },
  { code: "Lesotho", name: "Lesotho 🇱_s" },
  { code: "Liberia", name: "Liberia 🇱_r" },
  { code: "Libya", name: "Libya 🇱_y" },
  { code: "Liechtenstein", name: "Liechtenstein 🇱_i" },
  { code: "Lithuania", name: "Lithuania 🇱_t" },
  { code: "Luxembourg", name: "Luxembourg 🇱🇺" },
  { code: "Madagascar", name: "Madagascar 🇲_g" },
  { code: "Malawi", name: "Malawi 🇲_w" },
  { code: "Malaysia", name: "Malaysia 🇲🇾" },
  { code: "Maldives", name: "Maldives 🇲_v" },
  { code: "Mali", name: "Mali 🇲_l" },
  { code: "Malta", name: "Malta 🇲_t" },
  { code: "Marshall Islands", name: "Marshall Islands 🇲_h" },
  { code: "Mauritania", name: "Mauritania 🇲_r" },
  { code: "Mauritius", name: "Mauritius 🇲_u" },
  { code: "Mexico", name: "Mexico 🇲🇽" },
  { code: "Micronesia", name: "Micronesia 🇫_m" },
  { code: "Moldova", name: "Moldova 🇲_d" },
  { code: "Monaco", name: "Monaco 🇲_c" },
  { code: "Mongolia", name: "Mongolia 🇲_n" },
  { code: "Montenegro", name: "Montenegro 🇲_e" },
  { code: "Morocco", name: "Morocco 🇲🇦" },
  { code: "Mozambique", name: "Mozambique 🇲_z" },
  { code: "Myanmar", name: "Myanmar 🇲_m" },
  { code: "Namibia", name: "Namibia 🇳_a" },
  { code: "Nauru", name: "Nauru 🇳_r" },
  { code: "Nepal", name: "Nepal 🇳_p" },
  { code: "New Zealand", name: "New Zealand 🇳🇿" },
  { code: "Nicaragua", name: "Nicaragua 🇳_i" },
  { code: "Niger", name: "Niger 🇳_e" },
  { code: "Nigeria", name: "Nigeria 🇳🇬" },
  { code: "North Korea", name: "North Korea 🇰_p" },
  { code: "North Macedonia", name: "North Macedonia 🇲_k" },
  { code: "Oman", name: "Oman 🇴🇲" },
  { code: "Pakistan", name: "Pakistan 🇵🇰" },
  { code: "Palau", name: "Palau 🇵_w" },
  { code: "Palestine", name: "Palestine 🇵_s" },
  { code: "Panama", name: "Panama 🇵🇦" },
  { code: "Papua New Guinea", name: "Papua New Guinea 🇵_g" },
  { code: "Paraguay", name: "Paraguay 🇵_y" },
  { code: "Peru", name: "Peru 🇵🇪" },
  { code: "Philippines", name: "Philippines 🇵🇭" },
  { code: "Poland", name: "Poland 🇵🇱" },
  { code: "Portugal", name: "Portugal 🇵🇹" },
  { code: "Qatar", name: "Qatar 🇶🇦" },
  { code: "Romania", name: "Romania 🇷🇴" },
  { code: "Russia", name: "Russia 🇷🇺" },
  { code: "Rwanda", name: "Rwanda 🇷_w" },
  { code: "Saint Kitts and Nevis", name: "Saint Kitts & Nevis 🇰_n" },
  { code: "Saint Lucia", name: "Saint Lucia 🇱_c" },
  { code: "Saint Vincent and the Grenadines", name: "Saint Vincent 🇻_c" },
  { code: "Samoa", name: "Samoa 🇼_s" },
  { code: "San Marino", name: "San Marino 🇸_m" },
  { code: "Sao Tome and Principe", name: "Sao Tome & Principe 🇸_t" },
  { code: "Saudi Arabia", name: "Saudi Arabia 🇸🇦" },
  { code: "Senegal", name: "Senegal 🇸_n" },
  { code: "Serbia", name: "Serbia 🇷_s" },
  { code: "Seychelles", name: "Seychelles 🇸_c" },
  { code: "Sierra Leone", name: "Sierra Leone 🇸_l" },
  { code: "Slovakia", name: "Slovakia 🇸_k" },
  { code: "Slovenia", name: "Slovenia 🇸_i" },
  { code: "Solomon Islands", name: "Solomon Islands 🇸_b" },
  { code: "Somalia", name: "Somalia 🇸_o" },
  { code: "South Africa", name: "South Africa 🇿🇦" },
  { code: "South Sudan", name: "South Sudan 🇸_s" },
  { code: "Spain", name: "Spain 🇪🇸" },
  { code: "Sri Lanka", name: "Sri Lanka 🇱🇰" },
  { code: "Sudan", name: "Sudan 🇸_d" },
  { code: "Suriname", name: "Suriname 🇸_r" },
  { code: "Switzerland", name: "Switzerland 🇨🇭" },
  { code: "Syria", name: "Syria 🇸_y" },
  { code: "Taiwan", name: "Taiwan 🇹🇼" },
  { code: "Tajikistan", name: "Tajikistan 🇹_j" },
  { code: "Tanzania", name: "Tanzania 🇹_z" },
  { code: "Thailand", name: "Thailand 🇹🇭" },
  { code: "Timor-Leste", name: "Timor-Leste 🇹_l" },
  { code: "Togo", name: "Togo 🇹_g" },
  { code: "Tonga", name: "Tonga 🇹_o" },
  { code: "Trinidad and Tobago", name: "Trinidad & Tobago 🇹_t" },
  { code: "Tunisia", name: "Tunisia 🇹_n" },
  { code: "Turkey", name: "Turkey 🇹🇷" },
  { code: "Turkmenistan", name: "Turkmenistan 🇹_m" },
  { code: "Tuvalu", name: "Tuvalu 🇹_v" },
  { code: "Uganda", name: "Uganda 🇺_g" },
  { code: "Ukraine", name: "Ukraine 🇺🇦" },
  { code: "Uruguay", name: "Uruguay 🇺_y" },
  { code: "Uzbekistan", name: "Uzbekistan 🇺🇿" },
  { code: "Vanuatu", name: "Vanuatu 🇻_u" },
  { code: "Vatican City", name: "Vatican City 🇻_a" },
  { code: "Venezuela", name: "Venezuela 🇻_e" },
  { code: "Vietnam", name: "Vietnam 🇻🇳" },
  { code: "Yemen", name: "Yemen 🇾_e" },
  { code: "Zambia", name: "Zambia 🇿_m" },
  { code: "Zimbabwe", name: "Zimbabwe 🇿_w" }
];
