import React, { useState, useEffect } from 'react';
import { 
    Truck, Upload, Check, Sparkles, ArrowRight, ArrowLeft, 
    RefreshCcw, FileText, CheckCircle2 
} from 'lucide-react';
import SmartUploadPanel from '../upload/SmartUploadPanel';
import UniversalFileViewer from '../common/UniversalFileViewer';
import { generateDocNumber } from '../../lib/workflowV2Service';
import toast from 'react-hot-toast';

export default function StepDeliveryOrder({ 
    wizardData, 
    updateWizardData, 
    onNext, 
    onPrev,
    companyId 
}) {
    const [isUploadPanelOpen, setIsUploadPanelOpen] = useState(false);
    const [isGeneratingNo, setIsGeneratingNo] = useState(false);

    useEffect(() => {
        if (!wizardData.deliveryOrderNo && companyId) {
            autoGenerateDoNo();
        }
    }, [companyId]);

    const autoGenerateDoNo = async () => {
        setIsGeneratingNo(true);
        try {
            const nextNo = await generateDocNumber(companyId, 'Delivery Order');
            updateWizardData({ deliveryOrderNo: nextNo });
        } catch (err) {
            console.error('Error generating DO no:', err);
            updateWizardData({ deliveryOrderNo: `DO-${new Date().getFullYear()}-0001` });
        } finally {
            setIsGeneratingNo(false);
        }
    };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {/* Header */}
            <div style={{
                background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.08) 0%, rgba(5, 150, 105, 0.08) 100%)',
                border: '1px solid rgba(16, 185, 129, 0.2)',
                borderRadius: '16px',
                padding: '20px'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ background: '#10b981', color: '#fff', padding: '8px', borderRadius: '10px' }}>
                        <Truck size={22} />
                    </div>
                    <div>
                        <h2 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 800, color: 'var(--text-primary, #0f172a)' }}>
                            Step 5: Delivery Order &amp; Service Completion
                        </h2>
                        <span style={{ fontSize: '0.82rem', color: '#64748b' }}>
                            Upload customer signed Delivery Order or Service Report scan to confirm completed delivery.
                        </span>
                    </div>
                </div>
            </div>

            {/* DO Details Form */}
            <div style={{
                background: 'var(--card-bg, #fff)',
                border: '1px solid var(--border-color, #e2e8f0)',
                borderRadius: '16px',
                padding: '20px'
            }}>
                <h3 style={{ margin: '0 0 16px 0', fontSize: '1rem', fontWeight: 700 }}>
                    Delivery Order Details
                </h3>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
                    <div>
                        <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 700, marginBottom: '6px', color: '#475569' }}>
                            Incremental Delivery Order No *
                        </label>
                        <div style={{ display: 'flex', gap: '8px' }}>
                            <input
                                type="text"
                                value={wizardData.deliveryOrderNo || ''}
                                onChange={(e) => updateWizardData({ deliveryOrderNo: e.target.value })}
                                style={{
                                    width: '100%',
                                    padding: '10px 12px',
                                    borderRadius: '8px',
                                    border: '1px solid #cbd5e1',
                                    fontSize: '0.9rem',
                                    fontWeight: 800,
                                    background: '#f8fafc'
                                }}
                            />
                            <button
                                type="button"
                                onClick={autoGenerateDoNo}
                                disabled={isGeneratingNo}
                                style={{ background: '#f1f5f9', border: '1px solid #cbd5e1', borderRadius: '8px', padding: '0 12px', cursor: 'pointer' }}
                            >
                                <RefreshCcw size={16} className={isGeneratingNo ? 'animate-spin' : ''} />
                            </button>
                        </div>
                    </div>

                    <div>
                        <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 700, marginBottom: '6px', color: '#475569' }}>
                            Delivery Date
                        </label>
                        <input
                            type="date"
                            value={wizardData.deliveryDate || new Date().toISOString().split('T')[0]}
                            onChange={(e) => updateWizardData({ deliveryDate: e.target.value })}
                            style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #cbd5e1' }}
                        />
                    </div>

                    <div>
                        <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 700, marginBottom: '6px', color: '#475569' }}>
                            Received By (Customer Representative)
                        </label>
                        <input
                            type="text"
                            value={wizardData.receivedBy || ''}
                            onChange={(e) => updateWizardData({ receivedBy: e.target.value })}
                            placeholder="e.g. Chief Engineer John / Captain"
                            style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #cbd5e1' }}
                        />
                    </div>
                </div>
            </div>

            {/* Smart Upload Signed DO / Service Report */}
            <div style={{
                background: 'var(--card-bg, #fff)',
                border: '1px solid var(--border-color, #e2e8f0)',
                borderRadius: '16px',
                padding: '20px'
            }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                    <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 800 }}>
                        Step 5: Signed DO / Service Report Attachment
                    </h3>
                    <button
                        type="button"
                        onClick={() => setIsUploadPanelOpen(true)}
                        style={{ background: '#10b981', color: '#fff', border: 'none', borderRadius: '8px', padding: '8px 14px', fontSize: '0.82rem', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', boxShadow: '0 4px 12px rgba(16, 185, 129, 0.25)' }}
                    >
                        <Sparkles size={16} /> Smart Upload Signed DO
                    </button>
                </div>

                <UniversalFileViewer
                    file={wizardData.signedDoFile}
                    fileUrl={wizardData.signedDoUrl}
                    title="Signed Delivery Order & Service Proof Preview"
                    emptyTitle="No Signed DO Attached"
                    emptySubtitle="Upload signed Delivery Order scan or smartphone camera capture of delivery proof to preview loaded file here."
                    onRemove={() => {
                        updateWizardData({
                            signedDoFile: null,
                            signedDoUrl: ''
                        });
                        toast.info('Removed Signed DO file');
                    }}
                />
            </div>

            <SmartUploadPanel
                isOpen={isUploadPanelOpen}
                onClose={() => setIsUploadPanelOpen(false)}
                onSelect={(file) => {
                    updateWizardData({
                        signedDoFile: file.name || file.fileName,
                        signedDoUrl: file.webViewLink || file.previewUrl
                    });
                    toast.success("Attached Signed Delivery Order!");
                    setIsUploadPanelOpen(false);
                }}
                documentType="do"
            />

            {/* Navigation buttons */}
            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10px' }}>
                <button
                    onClick={onPrev}
                    style={{ background: '#f1f5f9', border: '1px solid #cbd5e1', borderRadius: '12px', padding: '12px 20px', fontSize: '0.88rem', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}
                >
                    <ArrowLeft size={18} /> Back
                </button>
                <button
                    onClick={onNext}
                    style={{ background: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)', color: '#fff', border: 'none', borderRadius: '12px', padding: '12px 24px', fontSize: '0.9rem', fontWeight: 800, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}
                >
                    Next Activity: Tax Invoicing <ArrowRight size={18} />
                </button>
            </div>
        </div>
    );
}
