// Singapore Coordinates
export const SG_LAT = 1.3521;
export const SG_LNG = 103.8198;

export interface Supplier {
  name: string;
  location: string;
  latitude: number;
  longitude: number;
  phoneNo: string;
  email: string;
  contactPerson: string;
  website: string;
  stockStatus: string;
  availableBrandsInfo: string;
  whyRecommended: string;
  industrySegment: string;
  supplierRole?: "Maker" | "Distributor" | "Agent" | "Stockist";
  address: string;
  price?: string;
  matchedProduct?: string;
}

export const PRESEEDED_SUPPLIERS: Supplier[] = [
  {
    name: "Keppel Offshore & Marine Spares Support",
    location: "Tuas, Singapore",
    latitude: 1.3200,
    longitude: 103.6400,
    phoneNo: "+65 6861 2244",
    email: "spares.support@keppelmarine.com.sg",
    contactPerson: "Mr. Tan Min Liang (Spares Procurement Manager)",
    website: "https://www.keppel.com/marine-spares",
    stockStatus: "In Stock - Immediate Dispatch",
    availableBrandsInfo: "Wartsila, Caterpillar, Rolls Royce Marine, Cummins, Woodward governors",
    whyRecommended: "Direct manufacturer authorized depot in Singapore specializing in deep-sea main propulsion engines, turbochargers, and heavy rigging machinery.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Maker",
    address: "51 Pioneer Sector 1, Jurong Industrial Estate, Singapore 628437"
  },
  {
    name: "Sembcorp Marine Supply & Engineering",
    location: "Admiralty Road, Singapore",
    latitude: 1.4440,
    longitude: 103.7840,
    phoneNo: "+65 6752 2222",
    email: "procurement@sembcorp-spares.sg",
    contactPerson: "Ms. Linda Ng (Senior Supply Director)",
    website: "https://www.sembcorp.com",
    stockStatus: "In Stock - 24/7 Delivery",
    availableBrandsInfo: "MAN Energy Solutions, Daihatsu parts, Yanmar engines, Kongsberg Maritime",
    whyRecommended: "Comprehensive maritime logistics hub in northern Singapore, stocked with custom crankshafts, engine pistons, and anchor chain assemblies.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Distributor",
    address: "80 Admiralty Road West, Sembawang Shipyard Sector, Singapore 759956"
  },
  {
    name: "Rotterdam Marine Seals & Pumps Corp",
    location: "Rotterdam Port, Netherlands",
    latitude: 51.9244,
    longitude: 4.4777,
    phoneNo: "+31 10 404 8922",
    email: "sales@rotterdamseals.nl",
    contactPerson: "Mr. Hans Vermeer (European Accounts Manager)",
    website: "https://www.rotterdamseals-marine.com",
    stockStatus: "3-5 Days International Shipping",
    availableBrandsInfo: "John Crane seals, Wika gauges, Grundfos pumps, Sulzer",
    whyRecommended: "Europe's largest seals depot with high-pressure fluid pumps and mechanical shaft gaskets compatible with LNG carriers and offshore jackup rigs.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Agent",
    address: "Albert Plesmanweg 73, Waalhaven South District, 3088 GB Rotterdam, Netherlands"
  },
  {
    name: "Singapore Automation Systems Pte Ltd",
    location: "Pioneer Road, Singapore",
    latitude: 1.3340,
    longitude: 103.6820,
    phoneNo: "+65 6265 1199",
    email: "sales@sgautomationsys.com",
    contactPerson: "Ms. Elena Seah (Industrial Sales Executive)",
    website: "https://www.sgautomationsys.com",
    stockStatus: "In Stock",
    availableBrandsInfo: "Siemens PLCs, Yokogawa transmitters, Honeywell control valves, Omron sensors",
    whyRecommended: "Premier industrial distributor located in Jurong industrial sector, specializing in automated sensor systems and calibrated process meters.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "25 Pioneer Crescent, Sector 3 Industrial Estate, Singapore 628554"
  },
  {
    name: "Duesseldorf Heavy Industry Valves",
    location: "Düsseldorf, Germany",
    latitude: 51.2277,
    longitude: 6.7735,
    phoneNo: "+49 211 908871",
    email: "export@duesseldorf-valves.de",
    contactPerson: "Dr. Dieter Krause (Chief Technical Sales)",
    website: "https://www.duesseldorf-valves.com",
    stockStatus: "Built-to-Order & Fast Freight",
    availableBrandsInfo: "Krone, Burkert, KSB Pumps, Samson control systems",
    whyRecommended: "Renowned German manufacturing facility supplying cryogenic valves and extreme-pressure actuators for industrial power stations.",
    industrySegment: "Industrial Spares",
    supplierRole: "Maker",
    address: "Grafenberger Allee 100, Flingern Nord, 40237 Düsseldorf, Germany"
  },
  {
    name: "Tokyo Precision Marine Gyros",
    location: "Ota-ku, Tokyo, Japan",
    latitude: 35.6528,
    longitude: 139.8394,
    phoneNo: "+81 3 5703 1155",
    email: "support@tokyo-precision-marine.jp",
    contactPerson: "Mr. Kenji Tanaka (Senior Navigation Expert)",
    website: "https://www.tokyoprecisiongyro.jp",
    stockStatus: "In Stock - Express DHL Available",
    availableBrandsInfo: "Tokimec, Anschuetz, Furuno, Sperry Marine",
    whyRecommended: "Japan-based navigation spare component specialist supporting fiber optic gyrocompasses, radar magnetrons, and autopilot electronic cards.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Agent",
    address: "4-16-1 Shinagawa Maritime Boulevard, Ota-ku, Tokyo 140-0002, Japan"
  },
  {
    name: "EcoMarine Hydrogen Fuel Systems",
    location: "CleanTech Loop, Singapore",
    latitude: 1.3500,
    longitude: 103.6900,
    phoneNo: "+65 6750 9001",
    email: "innovate@ecomarinehydrogen.sg",
    contactPerson: "Dr. Rachel Goh (Lead Innovation Engineer)",
    website: "https://www.ecomarinehydrogen.sg",
    stockStatus: "Available on Request (7 Days Lead)",
    availableBrandsInfo: "EcoFlow Marine, Ballard stacks, Toyota Hydrogen Core, Nel Electrolyzers",
    whyRecommended: "Singapore's dedicated green-shipping pioneer offering advanced hydrogen cell rebuild kits, carbon capture filters, and lightweight composite fuel valves.",
    industrySegment: "Innovative Spares",
    supplierRole: "Maker",
    address: "12 CleanTech Loop, Tower 2B #05-18, CleanTech Park, Singapore 637149"
  },
  {
    name: "Silicon Valley Fusion Spares Inc.",
    location: "San Jose, California, USA",
    latitude: 37.3382,
    longitude: -121.8863,
    phoneNo: "+1 408 555 0192",
    email: "orders@sv-fusionspares.com",
    contactPerson: "Mr. Dave Miller (Strategic Components Officer)",
    website: "https://www.sv-fusionspares.com",
    stockStatus: "Ships from USA in 5 Days",
    availableBrandsInfo: "Lockheed Fusion concepts, Tesla Industrial, Siemens Energy, Nvidia Quantum",
    whyRecommended: "Supplier of highly specialized, next-generation smart-grid capacitors, helium-cooled fusion rods, and IoT thermodynamic regulators.",
    industrySegment: "Innovative Spares",
    supplierRole: "Maker",
    address: "300 Park Avenue, Suite 1250, San Jose, CA 95110, USA"
  },
  {
    name: "Stockholm Smart Valve Technology",
    location: "Stockholm, Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    phoneNo: "+46 8 123 4567",
    email: "smartvalve@stockholminnovate.se",
    contactPerson: "Ms. Astrid Lindqvist (Director of OEM Relations)",
    website: "https://www.stockholminnovate.se",
    stockStatus: "In Stock - Climate Neutral Freight",
    availableBrandsInfo: "ABB Motors, Stockholm Valve Tech, Danfoss Smart Cores",
    whyRecommended: "Eco-friendly European developer of IoT-enabled pressure sensors and smart water treatment replacement actuators.",
    industrySegment: "Innovative Spares",
    supplierRole: "Maker",
    address: "Drottninggatan 10, Norrmalm Business Zone, 111 51 Stockholm, Sweden"
  },
  {
    name: "Jurong Seals & Bearings Pte Ltd",
    location: "Jurong East, Singapore",
    latitude: 1.3329,
    longitude: 103.7436,
    phoneNo: "+65 6563 8811",
    email: "info@jurongseals.com.sg",
    contactPerson: "Mr. Albert Ng (Managing Director)",
    website: "https://www.jurongseals.com",
    stockStatus: "In Stock",
    availableBrandsInfo: "SKF Bearings, NSK, FAG, Freudenberg seals, Parker Gaskets",
    whyRecommended: "Immediate, high-volume stock of standard dynamic shaft seals, high-temp hydraulic cylinders, and spherical bearings in Singapore.",
    industrySegment: "Common Spares",
    supplierRole: "Stockist",
    address: "10 Jurong Port Road, Berth 7 Logistics Hub, Singapore 619088"
  },
  {
    name: "Changi Fasteners & Brass Parts Ltd",
    location: "Changi South, Singapore",
    latitude: 1.3400,
    longitude: 103.9620,
    phoneNo: "+65 6542 9002",
    email: "sales@changifasteners.sg",
    contactPerson: "Mr. Joshua Lim (Operations Coordinator)",
    website: "https://www.changifasteners.sg",
    stockStatus: "In Stock - Bulk Pricing Available",
    availableBrandsInfo: "Wurth, Böllhoff fasteners, Hilti anchors",
    whyRecommended: "Massive East-Singapore warehouse offering stainless steel Grade 316 marine bolts, anchor rivets, and custom-bored brass nuts.",
    industrySegment: "Common Spares",
    supplierRole: "Stockist",
    address: "35 Changi South Street 1, Changi Industrial Estate, Singapore 486799"
  },
  {
    name: "Hamburg Mechanical Joints Co",
    location: "Hamburg Port, Germany",
    latitude: 53.5511,
    longitude: 9.9937,
    phoneNo: "+49 40 3344669",
    email: "contact@hamburgjoints.de",
    contactPerson: "Mr. Klaus Müller (Logistics Coordinator)",
    website: "https://www.hamburgjoints.com",
    stockStatus: "Overseas Dispatch in 48 Hours",
    availableBrandsInfo: "Nord-Lock wash, Loctite adhesive systems, Flexitall gaskets",
    whyRecommended: "High-spec industrial joining clamps, vibration-proof Nord-Lock washer systems, and metallic spiral gaskets for European chemical plants.",
    industrySegment: "Common Spares",
    supplierRole: "Stockist",
    address: "Kaiser-Wilhelm-Straße 50, Altona Logistics Terminal, 20355 Hamburg, Germany"
  },
  {
    name: "Shanghai Heavy Industrial Bearings Corp",
    location: "Pudong, Shanghai, China",
    latitude: 31.2304,
    longitude: 121.4737,
    phoneNo: "+86 21 6889 4432",
    email: "procurement@shanghaiheavybearing.cn",
    contactPerson: "Mr. Chen Wei (Overseas Dispatcher)",
    website: "https://www.shanghaiheavybearing.cn",
    stockStatus: "In Stock",
    availableBrandsInfo: "ZWZ bearings, SKF China, Timor Heavy Machining",
    whyRecommended: "Supplies massive heavy-duty slewing bearings, conveyor pillow blocks, and industrial gear assemblies directly from Pudong warehouses.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "600 Minsheng Road, Tower A #15-02, Pudong New Area, Shanghai 200135, China"
  },
  {
    name: "Dubai Industrial Spares & Hydraulics",
    location: "Jebel Ali Free Zone, Dubai, UAE",
    latitude: 25.2048,
    longitude: 55.2708,
    phoneNo: "+971 4 881 2290",
    email: "support@dubai-hydraulics.co.ae",
    contactPerson: "Mr. Fahad Al-Mansoori (B2B Accounts lead)",
    website: "https://www.dubaihosehydraulics.ae",
    stockStatus: "In Stock - Express Air Cargo",
    availableBrandsInfo: "Eaton Vickers, Gates hoses, Rexroth pumps, Sun Hydraulics",
    whyRecommended: "Based in Middle East's primary trade zone, delivering industrial high-pressure non-burst hydraulic hoses, manifolds, and directional valves.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "LOB 15, Office Suite 120, Jebel Ali Free Zone Authority, Dubai, UAE"
  },
  {
    name: "Houston Oilfield Equipment Spares",
    location: "Houston, Texas, USA",
    latitude: 29.7604,
    longitude: -95.3698,
    phoneNo: "+1 713 520 8899",
    email: "oilfield-spares@houstonequip.com",
    contactPerson: "Mr. Chuck Vance (Offshore Operations Liaison)",
    website: "https://www.houston-oilfieldspares.com",
    stockStatus: "Available on Demand",
    availableBrandsInfo: "Cameron blowout preventers, National Oilwell Varco (NOV), Baker Hughes",
    whyRecommended: "Specialist supply yard for petroleum drilling mud pump parts, BOP gaskets, pipeline drill collars, and heavy offshore pipe clamps.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Agent",
    address: "2001 Kirby Drive, Suite 400, Houston, TX 77019, USA"
  },
  {
    name: "Mumbai Marine Propellers & Auxiliary Spares",
    location: "Mumbai, India",
    latitude: 19.0760,
    longitude: 72.8777,
    phoneNo: "+91 22 2261 4040",
    email: "spares@mumbaimarinepropellers.in",
    contactPerson: "Mr. Rajesh K. Mehta (Commercial Director)",
    website: "https://www.mumbaimarinepropellers.in",
    stockStatus: "In Stock - Port of Mumbai Dispatch",
    availableBrandsInfo: "Yanmar engines, SKF India bearings, Kirloskar marine pumps",
    whyRecommended: "Authorized maritime parts broker in Mumbai specializing in ship propellors, drive shafts, and diesel generator rebuild kits.",
    industrySegment: "Marine & Offshore Spares",
    supplierRole: "Agent",
    address: "Standard Building, Ground Floor, Dr D.N. Road, Fort Port area, Mumbai, Maharashtra 400001, India"
  },
  {
    name: "Chennai Industrial Pneumatics & Valves",
    location: "Chennai, India",
    latitude: 13.0827,
    longitude: 80.2707,
    phoneNo: "+91 44 4355 9090",
    email: "industrial.pneumatics@chennaispares.co.in",
    contactPerson: "Ms. Ananya Sharma (Procurement Officer)",
    website: "https://www.chennaispneumatics.co.in",
    stockStatus: "In Stock - Express Dispatch",
    availableBrandsInfo: "Festo pneumatics, Janatics controls, Siemens motors, Danfoss valves",
    whyRecommended: "A high-capacity industrial hub supplying calibrated valve actuators, mechanical joints, and localized solenoid spares suitable for petrochemical plants.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "45 Anna Salai, Little Mount Industrial District, Chennai, Tamil Nadu 600015, India"
  },
  {
    name: "Gujarat Machinery & Forge Spares",
    location: "Gujarat, India",
    latitude: 23.0225,
    longitude: 72.5714,
    phoneNo: "+91 79 3280 1122",
    email: "exports@gujaratforgeandmachinery.com",
    contactPerson: "Mr. Hardik Patel (Head of International Logistics)",
    website: "https://www.gujaratforgeandmachinery.com",
    stockStatus: "Built-To-Order & Quick Freight",
    availableBrandsInfo: "Wuth fasteners, SKF India, L&T switchgear, Siemens PLCs",
    whyRecommended: "Specializes in high tensile forge fasteners, structural backing nuts, and customized dynamic heavy dynamic bearings under high load conditions.",
    industrySegment: "Common Spares",
    supplierRole: "Stockist",
    address: "102 GIDC Industrial Estate, Phase II, Vatva GIDC, Ahmedabad, Gujarat 382445, India"
  },
  {
    name: "Huntsmen (S) Pte Ltd",
    location: "Kaki Bukit, Singapore",
    latitude: 1.3486,
    longitude: 103.9068,
    phoneNo: "+65 6745 1121",
    email: "sales@huntsmen.com.sg",
    contactPerson: "Mr. Kelvin Aw (Managing Director)",
    website: "https://www.huntsmen.com.sg",
    stockStatus: "In Stock - Immediate Delivery",
    availableBrandsInfo: "PR electronics 4184, PR electronics 9106, Temperature and Pressure Transmitters",
    whyRecommended: "Singapore's trusted distributor for PR electronics industrial signal transmitters, specializing in uni-/bipolar signal conversion, isolate relays, and temperature converters.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "10 Kaki Bukit Road 1, #03-15 KB Industrial Building, Singapore 416175",
    price: "$317.48",
    matchedProduct: "PR electronics 4184 Universal Transmitter"
  },
  {
    name: "Dpstar Group Singapore",
    location: "Ubi Crescent, Singapore",
    latitude: 1.3289,
    longitude: 103.8988,
    phoneNo: "+65 6748 9390",
    email: "info@dpstar.com.sg",
    contactPerson: "Ms. Sarah Chen (Key Account Engineer)",
    website: "https://www.dpstar.com.sg",
    stockStatus: "In Stock",
    availableBrandsInfo: "PR electronics 4184, 9116 transmitters, temperature meters, level sensors, calibration tools",
    whyRecommended: "Specializes in high accuracy universal uni-/bipolar converters, isolating barriers, loop powered isolators, and customized thermal control cabinets.",
    industrySegment: "Industrial Spares",
    supplierRole: "Distributor",
    address: "81 Ubi Crescent, #01-12 Ubi Techpark, Singapore 408564",
    price: "$300.62",
    matchedProduct: "PR electronics 4184 Uni-/Bipolar Signal Converter"
  }
];
